
	/*
	 * This file was automatically generated by fixie.
	 * It contains a JavaScript array with the information to be passed to Lunr
	 * (https://lunrjs.com/) to provide a search feature via JavaScript.
	 */
	var searchDocuments = [{
		"id": "/404",
		"name": "Oops",
		"text": "oops whatever page you were looking for was not found. feel free to contact me at hector@hectorcorrea.com mailto:hector@hectorcorrea.com and ask the that originally. probably still exists but i did redirect it properly when migrated this site its current home. sorry about ------------------ oo / ----w"
	},{
		"id": "/about",
		"name": "About me",
		"text": "about me i am an assistant professor of educational leadership at the university hartford in west ct. for two decades have breathed learned and worked higher education. prior professional experience include a postdoctoral year as internal evaluator nsf advance grant virginia. project called uva charge aimed to increase recruitment retention success female urm faculty science technology engineering math stem social behavioral economic sbe sciences. before that ten years academic administrator saint paul school theology graduate-level kansas city mo. completed my ph.d. education pennsylvania state master s bachelor degree also colima méxico. training has prepared teach array topics. taught courses fall within three main areas competence: college teaching learning students experiences colleges universities research methods. guide supervise doctoral dissertations. comprises interwoven investigate how identities shape are shaped by their environments then inform decision making leads more inclusive universities. first area is located classroom seeks contribute all learners. second examines underrepresented members settings. third questions assessment approaches can supportive decisions. orcid id orcid.org/0000-0002-5073-5246 https://orcid.org/0000-0002-5073-5246"
	},{
		"id": "/index",
		"name": "Welcome",
		"text": "welcome to higher edding my corner of the web"
	},{
		"id": "/projects",
		"name": "Projects",
		"text": "projects content pending"
	},{
		"id": "/scholarship",
		"name": "Scholarship",
		"text": "scholarship content pending"
	},{
		"id": "/teaching",
		"name": "Teaching",
		"text": "teaching content pending"
	}];